import { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type AppLanguage = 'es' | 'ca' | 'en';

const translations: Record<AppLanguage, Record<string,string>> = {
  es: {},
  ca: {
    'Idioma':'Idioma','Español':'Espanyol','Català':'Català','English':'English',
    'Hoy':'Avui','Cuídate':'Cuida’t','Seguimiento':'Seguiment','Ajustes':'Configuració','Volver':'Tornar','Ir a la pantalla de inicio':'Anar a la pantalla d’inici',
    'Información que acompaña':'Informació que acompanya','Estoy aquí para ayudarte a comprender mejor lo que estás viviendo.':'Soc aquí per ajudar-te a comprendre millor el que estàs vivint.',
    'Buenos días':'Bon dia','Buenas tardes':'Bona tarda','Buenas noches':'Bona nit',
    '¿Cómo te encuentras hoy?':'Com et trobes avui?','Elige la opción que más se acerque a este momento.':'Tria l’opció que s’acosti més a aquest moment.',
    'Bien':'Bé','Regular':'Regular','Preocupado':'Preocupat','Necesito apoyo':'Necessito suport','Me encuentro con ánimo':'Em trobo amb ànims','Necesito bajar el ritmo':'Necessito abaixar el ritme','Hay algo que me inquieta':'Hi ha alguna cosa que m’inquieta','Quiero sentirme acompañado':'Vull sentir-me acompanyat',
    'Tu plan para hoy':'El teu pla per avui','Una propuesta sencilla para este momento':'Una proposta senzilla per a aquest moment',
    'El corazón de OncoResponde':'El cor d’OncoResponde','Háblame':'Parla’m','Cuéntame qué necesitas o qué te preocupa. Puedes hablar con tranquilidad o escribir; empezaremos por lo que hoy sea más importante para ti.':'Explica’m què necessites o què et preocupa. Pots parlar amb tranquil·litat o escriure; començarem pel que avui sigui més important per a tu.','Hablar':'Parlar','Escribir':'Escriure',
    'Ahora no sé qué preguntar. Ayúdame a empezar':'Ara no sé què preguntar. Ajuda’m a començar','Ver preguntas que pueden ayudarte a comenzar':'Veure preguntes que et poden ajudar a començar','Tengo una duda sobre mi tratamiento':'Tinc un dubte sobre el meu tractament','Me encuentro cansado':'Em trobo cansat','Explícame mi informe':'Explica’m el meu informe',
    'Tu minuto de hoy':'El teu minut d’avui','Escuchar':'Escoltar','Ver todos':'Veure’ls tots','Reiniciar':'Reiniciar','Reanudar':'Reprendre','Pausa':'Pausa','Detener':'Aturar','¿Te ha resultado útil?':'T’ha resultat útil?','Sí':'Sí','No':'No','Gracias. Tu valoración se guarda únicamente en este dispositivo.':'Gràcies. La teva valoració només es desa en aquest dispositiu.','¿Quieres preguntarme algo relacionado con este tema?':'Vols preguntar-me alguna cosa relacionada amb aquest tema?','Continuar la conversación':'Continuar la conversa',
    'Programa de 30 días':'Programa de 30 dies','Tu acompañamiento diario':'El teu acompanyament diari','Ver programa completo':'Veure el programa complet','Un paso cada día, a tu ritmo':'Un pas cada dia, al teu ritme','Encuentra una propuesta breve de escucha, calma o cuidado para acompañarte durante los próximos 30 días.':'Troba una proposta breu d’escolta, calma o cura per acompanyar-te durant els pròxims 30 dies.','Continuar mi acompañamiento':'Continuar el meu acompanyament',
    'Tu día':'El teu dia','Lo más relevante ahora':'El més rellevant ara','La información procede de lo que has guardado en este dispositivo.':'La informació prové del que has desat en aquest dispositiu.','Objetivo de hoy':'Objectiu d’avui','Un gesto sencillo':'Un gest senzill','Conseguido':'Assolit','Marcar como realizado':'Marcar com a fet','Últimos 7 días':'Últims 7 dies','Cómo te has encontrado':'Com t’has trobat','Este gráfico es orientativo y no realiza diagnósticos.':'Aquest gràfic és orientatiu i no fa diagnòstics.','Conversación contextual':'Conversa contextual','Habla sobre lo que necesites':'Parla sobre el que necessitis',
    'Explora a tu ritmo':'Explora al teu ritme','Todo lo que puede ayudarte':'Tot el que et pot ajudar','No necesitas descubrirlo todo hoy.':'No cal que ho descobreixis tot avui.',
    'Cuéntame sobre tu cáncer':'Explica’m el que saps del teu càncer','Mi tratamiento':'El meu tractament','Mi medicación':'La meva medicació','Comprende tus informes':'Comprèn els teus informes','Mi seguimiento':'El meu seguiment','Prepara tu consulta':'Prepara la teva consulta','Encuentra calma':'Troba calma','Mi camino':'El meu camí','Familia y cuidadores':'Família i cuidadors','Fuentes fiables':'Fonts fiables','Ayúdanos a mejorar':'Ajuda’ns a millorar','Ajustes y privacidad':'Configuració i privacitat',
    'Información orientativa basada en fuentes científicas y guías clínicas. No sustituye la valoración de tu equipo sanitario ni los servicios de urgencias.':'Informació orientativa basada en fonts científiques i guies clíniques. No substitueix la valoració del teu equip sanitari ni els serveis d’urgències.',
    'Puedes hablar con tranquilidad':'Pots parlar amb tranquil·litat','Tómate el tiempo que necesites. La conversación no se guarda automáticamente.':'Pren-te el temps que necessitis. La conversa no es desa automàticament.','Comenzar a hablar':'Començar a parlar','También puedes escribir…':'També pots escriure…','Enviar':'Enviar','Respuesta':'Resposta','Consultando OncoResponde…':'Consultant OncoResponde…','Lo más importante':'El més important','Qué puedes hacer':'Què pots fer','Cuándo consultar':'Quan consultar','Fuentes de referencia':'Fonts de referència','Cerrar y no guardar':'Tancar i no desar'
  },
  en: {
    'Idioma':'Language','Español':'Spanish','Català':'Catalan','English':'English',
    'Hoy':'Today','Cuídate':'Take care','Seguimiento':'Tracking','Ajustes':'Settings','Volver':'Back','Ir a la pantalla de inicio':'Go to home screen',
    'Información que acompaña':'Information that supports you','Estoy aquí para ayudarte a comprender mejor lo que estás viviendo.':'I am here to help you better understand what you are going through.',
    'Buenos días':'Good morning','Buenas tardes':'Good afternoon','Buenas noches':'Good evening',
    '¿Cómo te encuentras hoy?':'How are you feeling today?','Elige la opción que más se acerque a este momento.':'Choose the option that best matches how you feel right now.',
    'Bien':'Well','Regular':'So-so','Preocupado':'Worried','Necesito apoyo':'I need support','Me encuentro con ánimo':'I feel in good spirits','Necesito bajar el ritmo':'I need to slow down','Hay algo que me inquieta':'Something is worrying me','Quiero sentirme acompañado':'I want to feel supported',
    'Tu plan para hoy':'Your plan for today','Una propuesta sencilla para este momento':'A simple suggestion for this moment',
    'El corazón de OncoResponde':'The heart of OncoResponde','Háblame':'Talk to me','Cuéntame qué necesitas o qué te preocupa. Puedes hablar con tranquilidad o escribir; empezaremos por lo que hoy sea más importante para ti.':'Tell me what you need or what is worrying you. You can speak calmly or write; we will start with what matters most to you today.','Hablar':'Speak','Escribir':'Write',
    'Ahora no sé qué preguntar. Ayúdame a empezar':'I do not know what to ask. Help me get started','Ver preguntas que pueden ayudarte a comenzar':'See questions that can help you get started','Tengo una duda sobre mi tratamiento':'I have a question about my treatment','Me encuentro cansado':'I feel tired','Explícame mi informe':'Explain my report',
    'Tu minuto de hoy':'Your minute today','Escuchar':'Listen','Ver todos':'View all','Reiniciar':'Restart','Reanudar':'Resume','Pausa':'Pause','Detener':'Stop','¿Te ha resultado útil?':'Was this helpful?','Sí':'Yes','No':'No','Gracias. Tu valoración se guarda únicamente en este dispositivo.':'Thank you. Your rating is stored only on this device.','¿Quieres preguntarme algo relacionado con este tema?':'Would you like to ask me something about this topic?','Continuar la conversación':'Continue the conversation',
    'Programa de 30 días':'30-day programme','Tu acompañamiento diario':'Your daily support','Ver programa completo':'View full programme','Un paso cada día, a tu ritmo':'One step each day, at your own pace','Encuentra una propuesta breve de escucha, calma o cuidado para acompañarte durante los próximos 30 días.':'Find a brief listening, calming or self-care suggestion to support you over the next 30 days.','Continuar mi acompañamiento':'Continue my support programme',
    'Tu día':'Your day','Lo más relevante ahora':'What matters most now','La información procede de lo que has guardado en este dispositivo.':'This information comes from what you have saved on this device.','Objetivo de hoy':'Today’s goal','Un gesto sencillo':'One simple step','Conseguido':'Completed','Marcar como realizado':'Mark as done','Últimos 7 días':'Last 7 days','Cómo te has encontrado':'How you have felt','Este gráfico es orientativo y no realiza diagnósticos.':'This chart is for guidance only and does not provide a diagnosis.','Conversación contextual':'Context-aware conversation','Habla sobre lo que necesites':'Talk about whatever you need',
    'Explora a tu ritmo':'Explore at your own pace','Todo lo que puede ayudarte':'Everything that may help you','No necesitas descubrirlo todo hoy.':'You do not need to explore everything today.',
    'Cuéntame sobre tu cáncer':'Tell me what you know about your cancer','Mi tratamiento':'My treatment','Mi medicación':'My medication','Comprende tus informes':'Understand your reports','Mi seguimiento':'My tracking','Prepara tu consulta':'Prepare your appointment','Encuentra calma':'Find calm','Mi camino':'My journey','Familia y cuidadores':'Family and carers','Fuentes fiables':'Trusted sources','Ayúdanos a mejorar':'Help us improve','Ajustes y privacidad':'Settings and privacy',
    'Información orientativa basada en fuentes científicas y guías clínicas. No sustituye la valoración de tu equipo sanitario ni los servicios de urgencias.':'General guidance based on scientific sources and clinical guidelines. It does not replace assessment by your healthcare team or emergency services.',
    'Puedes hablar con tranquilidad':'You can speak freely','Tómate el tiempo que necesites. La conversación no se guarda automáticamente.':'Take all the time you need. The conversation is not saved automatically.','Comenzar a hablar':'Start speaking','También puedes escribir…':'You can also write…','Enviar':'Send','Respuesta':'Answer','Consultando OncoResponde…':'Consulting OncoResponde…','Lo más importante':'Most important','Qué puedes hacer':'What you can do','Cuándo consultar':'When to seek advice','Fuentes de referencia':'Reference sources','Cerrar y no guardar':'Close without saving'
  }
};

type LanguageContextValue = { language: AppLanguage; setLanguage: (language: AppLanguage) => void; t: (text:string) => string; locale: string };
const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({children}:{children:React.ReactNode}) {
  const [language,setLanguageState] = useState<AppLanguage>(() => (localStorage.getItem('oncoresponde:language') as AppLanguage) || 'es');
  const setLanguage = (next:AppLanguage) => { localStorage.setItem('oncoresponde:language', next); setLanguageState(next); };
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  const value = useMemo(() => ({language,setLanguage,t:(text:string)=>translations[language][text] || text,locale:language==='ca'?'ca-ES':language==='en'?'en-GB':'es-ES'}), [language]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}
export function useLanguage(){ const ctx=useContext(LanguageContext); if(!ctx) throw new Error('useLanguage must be used inside LanguageProvider'); return ctx; }
